services:
  marktguru.api:
    image: marktguru-api
    build:
      context: .
      dockerfile: Marktguru.API/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=80
        - ASPNETCORE_HTTPS_PORTS=443
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/marktguru-api.pfx
        - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:80"
      - "5001:443"

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
